[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "php init-db.php"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
